package org.jfxcore.fxml.annotator;

import com.intellij.codeInspection.LocalInspectionTool;
import com.intellij.codeInspection.ProblemHighlightType;
import com.intellij.codeInspection.ProblemsHolder;
import com.intellij.psi.JavaElementVisitor;
import com.intellij.psi.PsiClass;
import com.intellij.psi.PsiElementVisitor;
import com.intellij.psi.PsiFile;
import com.intellij.psi.PsiJavaCodeReferenceElement;
import com.intellij.psi.PsiReferenceList;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.kotlin.asJava.LightClassUtilsKt;
import org.jetbrains.kotlin.psi.KtClass;
import org.jetbrains.kotlin.psi.KtSimpleNameExpression;
import org.jetbrains.kotlin.psi.KtUserType;
import org.jetbrains.kotlin.psi.KtVisitorVoid;
import org.jfxcore.fxml.lang.Fxml2EmbeddedUtil;

/**
 * Inspection that adds an actionable hint when the base class generated by the FXML
 * compiler ({@code {ClassName}Base}) cannot be resolved in a
 * {@code @ComponentView}-annotated class.
 *
 * <p>The base class is absent when the FXML compiler's annotation processor has not run
 * yet. The hint directs the developer to rebuild with annotation processing enabled
 * and provides a link to the documentation.
 *
 * <p>Fires on the unresolved {@code {ClassName}Base} reference in the {@code extends}
 * clause (Java) or supertype list (Kotlin) of a {@code @ComponentView}-annotated class.
 *
 * <p>Suppression:
 * <ul>
 *   <li>Java: {@code @SuppressWarnings("Fxml2AnnotationProcessingHint")} on the class</li>
 *   <li>Kotlin: {@code @Suppress("Fxml2AnnotationProcessingHint")} on the class</li>
 * </ul>
 */
public final class Fxml2AnnotationProcessingHintInspection extends LocalInspectionTool {

    /** Short name used for suppression annotations and the inspection profile key. */
    public static final String SHORT_NAME = "Fxml2AnnotationProcessingHint";

    /** URL of the fxml-compiler documentation page for embedded FXML components. */
    public static final String DOCS_URL =
            "https://jfxcore.github.io/fxml-compiler/getting-started/embedded.html";

    /** Suffix appended to the hint message. */
    private static final String REBUILD_SUFFIX =
            " Rebuilding with annotation processing is required."
            + " See: " + DOCS_URL;

    // -----------------------------------------------------------------------
    // LocalInspectionTool contract

    @Override
    public @NotNull String getShortName() {
        return SHORT_NAME;
    }

    @Override
    public @NotNull PsiElementVisitor buildVisitor(
            @NotNull ProblemsHolder holder, boolean isOnTheFly) {

        PsiFile file = holder.getFile();
        String name = file.getName();

        if (name.endsWith(".java")) {
            return new JavaElementVisitor() {
                @Override
                public void visitClass(@NotNull PsiClass psiClass) {
                    checkUnresolvedBaseClass(psiClass, holder);
                }
            };
        }

        if (name.endsWith(".kt")) {
            try {
                return new KtVisitorVoid() {
                    @Override
                    public void visitClass(@NotNull KtClass ktClass) {
                        checkKotlinUnresolvedBaseClass(ktClass, holder);
                    }
                };
            } catch (NoClassDefFoundError ignored) {
                // Kotlin plugin not available, degrade gracefully
                return PsiElementVisitor.EMPTY_VISITOR;
            }
        }

        return PsiElementVisitor.EMPTY_VISITOR;
    }

    // -----------------------------------------------------------------------
    // Kotlin: unresolved {ClassName}Base in the supertype list

    private static void checkKotlinUnresolvedBaseClass(
            @NotNull KtClass ktClass, @NotNull ProblemsHolder holder) {

        var lightClass = LightClassUtilsKt.toLightClass(ktClass);
        if (lightClass == null) return;
        if (!lightClass.hasAnnotation(Fxml2EmbeddedUtil.MARKUP_ANNOTATION_FQN)) return;

        String className = ktClass.getName();
        if (className == null) return;
        String expectedBase = className + "Base";

        for (var entry : ktClass.getSuperTypeListEntries()) {
            var typeRef = entry.getTypeReference();
            if (typeRef == null) continue;
            var typeEl = typeRef.getTypeElement();
            if (!(typeEl instanceof KtUserType userType)) continue;
            if (!expectedBase.equals(userType.getReferencedName())) continue;

            KtSimpleNameExpression refExpr = userType.getReferenceExpression();
            if (refExpr == null) continue;
            // Use getReferences() instead of the deprecated getReference() on KtElement.
            var psiRefs = refExpr.getReferences();
            if (psiRefs.length > 0 && psiRefs[0].resolve() != null) continue; // already resolved

            holder.registerProblem(
                    refExpr,
                    "'" + expectedBase + "' was not yet generated by the FXML/2 compiler."
                    + REBUILD_SUFFIX,
                    ProblemHighlightType.WARNING);
        }
    }

    // -----------------------------------------------------------------------
    // Java: unresolved {ClassName}Base in the extends clause

    private static void checkUnresolvedBaseClass(
            @NotNull PsiClass psiClass, @NotNull ProblemsHolder holder) {

        if (!psiClass.hasAnnotation(Fxml2EmbeddedUtil.MARKUP_ANNOTATION_FQN)) return;

        String className = psiClass.getName();
        if (className == null) return;
        String expectedBase = className + "Base";

        PsiReferenceList extendsList = psiClass.getExtendsList();
        if (extendsList == null) return;

        for (PsiJavaCodeReferenceElement ref : extendsList.getReferenceElements()) {
            if (!expectedBase.equals(ref.getReferenceName())) continue;
            if (ref.resolve() != null) continue; // already resolved, no hint needed

            holder.registerProblem(
                    ref,
                    "'" + expectedBase + "' was not yet generated by the FXML/2 compiler."
                    + REBUILD_SUFFIX,
                    ProblemHighlightType.WARNING);
        }
    }
}
