name: CI publish

on:
  push:
    tags:
      - '*'

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v6

  build:
    name: Build and publish
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25.0.3'

      - name: Run Gradle build
        run: ./gradlew publishPlugin -x test -PTAG_VERSION=${VERSION}
        env:
          VERSION: ${{ github.ref_name }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.INTELLIJ_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.INTELLIJ_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_certificateChain: ${{ secrets.INTELLIJ_CERTIFICATE_CHAIN }}
          ORG_GRADLE_PROJECT_publishingToken: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
